
export const individualPlans = [
  {
    name: 'Free',
    tier: 'free',
    price: '$0',
    period: 'forever',
    description: 'Perfect for learning and experimenting',
    features: [
      '3 public projects',
      '100 MB storage',
      'Community support',
      'Basic code editor',
      '5 monthly deploys',
      'Standard templates'
    ],
    buttonText: 'Get Started Free',
    popular: false,
    highlight: 'Great for beginners',
  },
  {
    name: 'Starter',
    tier: 'starter',
    monthlyPrice: 5,
    annualPrice: 48,
    period: 'month',
    description: 'Essential tools for serious developers',
    features: [
      'Unlimited private projects',
      '2 GB storage',
      'Email support',
      'Custom domains (1)',
      '25 monthly deploys',
      'Premium templates',
      'Basic AI assistance',
      'Export projects'
    ],
    buttonText: 'Start Building',
    popular: false,
    highlight: 'Most popular for individuals',
  },
  {
    name: 'Developer',
    tier: 'developer',
    monthlyPrice: 9,
    annualPrice: 84,
    period: 'month',
    description: 'Advanced features for professionals',
    features: [
      'Everything in Starter',
      '10 GB storage',
      'Advanced AI code assistant',
      'Git integration & sync',
      'Custom domains (5)',
      '100 monthly deploys',
      'Priority support',
      'Advanced analytics',
      'Custom integrations'
    ],
    buttonText: 'Go Professional',
    popular: true,
    highlight: 'Best value for professionals',
  },
  {
    name: 'Pro',
    tier: 'pro',
    monthlyPrice: 19,
    annualPrice: 180,
    period: 'month',
    description: 'Everything you need to scale',
    features: [
      'Everything in Developer',
      '50 GB storage',
      'Unlimited deploys',
      'White-label options',
      'Custom domains (unlimited)',
      'Advanced analytics & insights',
      '24/7 priority support',
      'Custom AI training',
      'Enterprise integrations'
    ],
    buttonText: 'Scale Up',
    popular: false,
    highlight: 'Maximum power & flexibility',
  }
];

export const teamPlans = [
  {
    name: 'Team Starter',
    tier: 'team-starter',
    monthlyPrice: 15,
    annualPrice: 144,
    period: 'month',
    description: 'Collaboration for small teams',
    features: [
      'All Developer features',
      '5 team members',
      '25 GB shared storage',
      'Team project management',
      'Shared component library',
      'Team analytics dashboard',
      'Role-based permissions',
      'Slack integration'
    ],
    buttonText: 'Start Collaborating',
    userCount: '5 users',
    popular: false,
    highlight: 'Perfect for small teams',
  },
  {
    name: 'Team Pro',
    tier: 'team-pro',
    monthlyPrice: 35,
    annualPrice: 336,
    period: 'month',
    description: 'Advanced collaboration tools',
    features: [
      'All Pro features',
      '15 team members',
      '100 GB shared storage',
      'Advanced permissions',
      'Custom workflows',
      'Team training sessions',
      'Dedicated account manager',
      'Advanced integrations'
    ],
    buttonText: 'Boost Productivity',
    userCount: '15 users',
    popular: true,
    highlight: 'Most popular for teams',
  },
  {
    name: 'Enterprise',
    tier: 'enterprise',
    price: 'Custom',
    period: 'contact us',
    description: 'Tailored for large organizations',
    features: [
      'Unlimited team members',
      'Unlimited storage',
      'Custom integrations',
      'SSO & compliance (SAML)',
      'Dedicated infrastructure',
      'SLA guarantees',
      '24/7 phone support',
      'Custom onboarding'
    ],
    buttonText: 'Contact Sales',
    userCount: 'Unlimited',
    popular: false,
    highlight: 'Enterprise-grade security',
  }
];
